// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using SmartLibrary.Data;

#nullable disable

namespace SmartLibrary.Migrations
{
    [DbContext(typeof(SmartLibraryDbContext))]
    partial class SmartLibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartLibrary.Models.Kaynak", b =>
                {
                    b.Property<string>("ISBN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Kategori")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KaynakTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OduncDurumu")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OduncTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("OkunmaSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime>("YayinTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Yazar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ISBN");

                    b.ToTable("Kaynaklar");

                    b.HasDiscriminator<string>("KaynakTuru");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SmartLibrary.Models.Kullanici", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FavoriKategoriler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IlgiAlanlari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Yas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("SmartLibrary.Models.OduncKaydi", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OduncTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IadeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kategori")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KaynakBaslik")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("KullaniciId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KullaniciIdAktif")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TeslimSuresi")
                        .HasColumnType("int");

                    b.HasKey("ISBN", "OduncTarihi");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("KullaniciIdAktif");

                    b.ToTable("OduncKayitlari");
                });

            modelBuilder.Entity("SmartLibrary.Patterns.Singleton.IslemKaydi", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IslemTuru")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("IslemKayitlari");
                });

            modelBuilder.Entity("SmartLibrary.Models.Dergi", b =>
                {
                    b.HasBaseType("SmartLibrary.Models.Kaynak");

                    b.Property<string>("ISSN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SayiNo")
                        .HasColumnType("int");

                    b.Property<string>("YayinPeriyodu")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Dergi");
                });

            modelBuilder.Entity("SmartLibrary.Models.Kitap", b =>
                {
                    b.HasBaseType("SmartLibrary.Models.Kaynak");

                    b.Property<string>("Dil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SayfaSayisi")
                        .HasColumnType("int");

                    b.Property<string>("YayinEvi")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Kitap");
                });

            modelBuilder.Entity("SmartLibrary.Models.Tez", b =>
                {
                    b.HasBaseType("SmartLibrary.Models.Kaynak");

                    b.Property<string>("Bolum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DanismanAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TezTuru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Universite")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Tez");
                });

            modelBuilder.Entity("SmartLibrary.Models.OduncKaydi", b =>
                {
                    b.HasOne("SmartLibrary.Models.Kullanici", null)
                        .WithMany("OduncGecmisi")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SmartLibrary.Models.Kullanici", null)
                        .WithMany("AktifOduncler")
                        .HasForeignKey("KullaniciIdAktif")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SmartLibrary.Models.Kullanici", b =>
                {
                    b.Navigation("AktifOduncler");

                    b.Navigation("OduncGecmisi");
                });
#pragma warning restore 612, 618
        }
    }
}

